---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: rhacm-policies
  name: rhacm-policies-placement-1
  namespace: default
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'local-cluster'
              operator: 'In'
              values: 
                - 'true'
  clusterSets:
    - global
    - default
